print("Welcome to the tip calculator")
bill = float(input("What was the total bill $"))
perc = int(input("What percentage would you like to give? 10, 12, 15?"))
people = int(input("How many people to split?"))
output = print("Each person should pay: $")